services:
  eureka-server:
    image: osantamaria/ntd-eureka-server:latest
    container_name: ntd-eureka-server
    ports:
      - "8761:8761"
    environment:
      - spring.application.name=ntd-eureka-server
      - spring.client.registerWithEureka=false
      - eureka.client.fetchRegistry=false
      - eureka.server.waitTimeInMsWhenSyncEmpty=0
    networks:
      - eureka-network

  api-gateway:
    image: osantamaria/ntd-api-gateway:latest
    container_name: ntd-api-gateway
    ports:
      - "8080:8080"
    environment:
      - eureka.instance.preferIpAddress=true
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    networks:
      - eureka-network
    depends_on:
      - eureka-server

  authorization-service:
    image: osantamaria/ntd-authorization-service:latest
    container_name: ntd-authorization-service
    ports:
      - "8081:8081"
    environment:
      - eureka.instance.preferIpAddress=true
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
    networks:
      - eureka-network
    depends_on:
      - eureka-server

  user-service:
    image: osantamaria/ntd-user-service:latest
    container_name: ntd-user-service
    ports:
      - "8082:8082"
    environment:
      - eureka.instance.preferIpAddress=true
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/calculatordb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    networks:
      - eureka-network
    depends_on:
      - eureka-server

  calculator-service:
    image: osantamaria/ntd-calculator-service:latest
    container_name: ntd-calculator-service
    ports:
      - "8083:8083"
    environment:
      - eureka.instance.preferIpAddress=true
      - eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka
      - spring.datasource.url=jdbc:mysql://host.docker.internal:3306/calculatordb?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    networks:
      - eureka-network
    depends_on:
      - eureka-server
      - user-service

networks:
  eureka-network: